Includes ast.Node.ContentEquals method
arr-ai/wbnf pull request #51
Opened 2020-03-11 21:37 UTC by andrewemeryanz

Included to test equality of node content independently of the
scanners used to parse them. Included to provide alternative approach
to Scanner.StripSource for testing equality.

2020-03-12 00:02 UTC, ghost requested changes
Minor changes requested.

2020-03-12 00:02 UTC, ghost commented on ast/node.go
> +				if otherNodes == nil || len(nodes) != len(otherNodes) {
comment and nil check unnecessary. `len(nil) == 0`

2020-03-12 00:02 UTC, ghost commented on ast/node.go
> +	switch other.(type) {
`switch other := other.(type)` so you don't need to the same thing in line 192

Same in the Leaf and Extra switches

2020-03-13 01:03 UTC, ghost approved these changes

2020-03-13 01:03 UTC, anz-gordonj7 commented
Please reply to all comments in the future

2020-03-15 23:57 UTC, marcelocantos approved these changes

2020-03-16 22:16 UTC, merged