Bold context filename text
arr-ai/wbnf pull request #69
Opened 2020-04-22 05:50 UTC by ChloePlanet

2020-04-24 02:39 UTC, marcelocantos requested changes

2020-04-24 02:39 UTC, marcelocantos commented on ast/node_string.go
> +	}
nit: `make([]parser.Scanner, 0, len(c)) ... append` is more idiomatic.

2020-04-24 02:39 UTC, marcelocantos commented on parser/scanner.go
> +		return errors.New("merge needs at least two scanners")
`len(items) == 1` is a degenerate case, but still valid.

2020-04-24 02:39 UTC, marcelocantos commented on parser/scanner.go
> +func (s *Scanner) Merge(items []Scanner) error {
Prefer a more functional approach:
```suggestion
func MergeScanners(items ...Scanner) (Scanner, error) {
```

2020-04-24 03:50 UTC, marcelocantos submitted a review, later dismissed

2020-04-25 07:05 UTC, marcelocantos submitted a review, later dismissed
One or two negative tests (no leaves) would be good.

2020-04-27 07:20 UTC, anzdaddy submitted a review, later dismissed

2020-04-27 07:32 UTC, marcelocantos approved these changes

2020-04-27 07:35 UTC, merged